branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: oministack-dev
global:
  application_name: oministack
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
